{% set version = "1.8-5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-terra
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/terra_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/terra/terra_{{ version }}.tar.gz
  sha256: b05e0fe5e4ec7916b85673498191db48c8ed762cae035bb52dc941f79c8d5f2e
  patches:
    - patches/0001-minimal-ucrt-libs.patch

build:
  skip: true  # [ppc64le]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('r_clang') }}    # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=1.0_10
    - libgdal-core
    - proj
    - geos
  run:
    - r-base
    - r-rcpp >=1.0_10

test:
  requires:
    - r-tinytest
  commands:
    - $R -e "library('terra')"           # [not win]
    - "\"%R%\" -e \"library('terra')\""  # [win]
    - $R -e "tinytest::test_package('terra')"           # [not win]
    - "\"%R%\" -e \"tinytest::test_package('terra')\""  # [win]

about:
  home: https://rspatial.org/terra
  dev_url: https://github.com/rspatial/terra
  license: GPL-3.0-or-later
  summary: Methods for spatial data analysis with raster and vector data. Raster methods allow for low-level data manipulation as well as high-level global, local, zonal, and focal computation. The predict and interpolate methods facilitate the use of regression type (interpolation, machine learning) models for spatial prediction,
    including with satellite remote sensing data. Processing of very large files is supported. See the manual and tutorials on <https://rspatial.org/terra/> to get started. 'terra' is very similar to the 'raster' package; but 'terra' can do more, is simpler to use, and it is faster.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - TomAugspurger
